# Generated by Django 5.0.6 on 2024-07-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
